services:
  mongodb-botiga:
    image: mongo:7.0
    container_name: mongodb-botiga
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - xarxa-botiga

  mongoexpress-botiga:
    image: mongo-express:1.0
    container_name: mongoexpress-botiga
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-botiga
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongodb-botiga:27017/
    networks:
      - xarxa-botiga

networks:
  xarxa-botiga:
    name: xarxa-botiga